### ISSUE TITLE
Last reset time is not always correct

### ISSUE THREAD

**Issue by atlochowski** [monich/harbour-counter#10]
It's a minor bug  but still a bug.
When you create new couter, last reset time is empty but when you start counting last reset will be set to last change time. In my opinion it should stay empty.

**Comment by monich** [comment]
If we define reset time as the last time when you pressed the reset button, then if you never pressed it then it should stay empty... that sounds reasonable. I'll think about it a bit more but your suggestion does seem to make sense.

**Comment by monich** [comment]
I changed the behavior in 993d4ca. Similarly, the last change time now stays empty after reset until you modify the counter's value.
