### ISSUE TITLE
Version number in Jolla Store is different than in OpenRepos.

### ISSUE THREAD

**Issue by atlochowski** [monich/harbour-counter#12]
In OpenRepos version is 1.0.4-8.1 but in Jolla Store 1.0.5.
So every time I open Jolla store I have notification that there is newer version of Counter.

**Comment by monich** [comment]
Yeah, the 1.0.4 => 1.0.5 change was so minimal that I didn't bother updating the openrepos version. Hold on, I'll build 1.0.6 soon and publish it in both places. Possibly today. After work :)

**Comment by atlochowski** [comment]
ok. sorry for being annoying.

**Comment by monich** [comment]
Version 1.0.6 has been pushed to openrepos! (and submitted to Jolla Store too).
